Add serverPath option
wasm-tool/rollup-plugin-rust pull request #18
Opened 2021-03-10 14:09 UTC by domoritz

Follow up from #12

2021-03-27 17:08 UTC, Pauan requested changes
Overall this looks good, just one minor change.

2021-03-27 17:08 UTC, Pauan commented on index.js
> +                            path = serverPath + path.split('/').pop();
```suggestion
                            path = serverPath + /[^\/\\]*$/.exec(path)[0];
```

I think we should handle `\` as well, for extra robustness.

2021-03-27 23:18 UTC, domoritz commented
Great. I added your suggestion.

2021-03-28 09:52 UTC, merged

2021-03-28 09:52 UTC, Pauan commented
Thanks!