Updated to wasm-pack 0.10.0
wasm-tool/rollup-plugin-rust pull request #21
Opened 2021-07-02 18:37 UTC by simlay

Resolves security issue from rustwasm/wasm-pack#958

2021-07-03 08:47 UTC, Pauan requested changes

2021-07-03 08:47 UTC, Pauan commented on example/package.json
> +    "@wasm-tool/rollup-plugin-rust": "file:..",
I prefer for the example to be self-contained, so it will work even if the user copy-pastes it into their own project.

2021-07-03 08:47 UTC, Pauan commented on package.json
> +  "version": "1.0.7",
Please don't bump the version, I do that right before releasing.

2021-07-03 09:33 UTC, Pauan commented on example/package.json
> +    "@wasm-tool/rollup-plugin-rust": "file:..",
(Also note that if you want to test locally, you can use [`yarn link`](https://classic.yarnpkg.com/en/docs/cli/link) to override `@wasm-tool/rollup-plugin-rust` with the local version)

2021-07-03 17:24 UTC, merged

2021-07-03 17:24 UTC, Pauan commented
Thanks!

2021-07-08 00:23 UTC, simlay commented
@Pauan Would you be up to publish a new release to npmjs?

2021-07-08 00:50 UTC, Pauan commented
@simlay Yeah, sorry for the delay, I need to update my npm first, since yarn isn't allowing me to publish.

2021-07-08 11:07 UTC, Pauan commented
I published version 1.0.7.